baseURL = "/"
languageCode = "en-us"
title = "Execute Big"

disableHugoGeneratorInject = true

[params]
  [params.tracking] 
    id = "837ce14a-7f21-44d1-a621-5f048aceda2c"

  [params.stripe]
    testKey = "pk_test_51HFmyUGd5RDXy0STaqkryz2uhc4LjMMkAeeMenLrDFAKdsWRaB5iWBLOkmR1KOD39liVOD2JK9Q930qHbcJiFNmq00Pxo6VlMp"
    pubKey = "pk_live_51HFmyUGd5RDXy0STk1dGHANECh5LHKThHSHj3KvpMRPsoM4GbRjpuJKBrPtIJ3B8rkATb1zASRFuabQUWsu1PMr600Tj5wMNAZ"

  [params.announcement]
    show = true

  [params.logo]
    mobile = "images/logo-mobile.svg"
    desktop = "images/logo.svg"
    desktop_height = "36px"
    alt = "Execute Big Pig"

  [params.homepage_meta_tags]
    meta_description = "A minimal & transparent student-run organization founded to enable all students to experience and explore computer science education."
    meta_og_title = "Execute Big"
    meta_og_type = "website"
    meta_og_url = "https://executebig.org"
    meta_og_image = "https://executebig.org/banner.png"
    meta_og_description = "A minimal & transparent student-run organization founded to enable all students to experience and explore computer science education."
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@executebig"
    meta_twitter_creator = "@executebig"

  [params.footer]
    copyright_text = '&copy;2020 Execute Big.'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Programs"
    url = "/programs/"
      weight = 1

  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 2

  # Footer Menu
  [[menu.footer]]
    name = "Donate"
    url = "/donate/"
      weight = 2
